### ISSUE TITLE
[PE-D][Tester D] Able to add and edit transactions to be 0

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S1-CS2103-T16-3/tp#151]
![image.png](https://raw.githubusercontent.com/sudarshan2401/ped/main/files/40c7980a-a381-4f67-8cba-8914db5f1cad.png)

Unsure why users would need to track transactions that would be of no amount. 

Replicated by:
Using add command with 0 as amt/ parameter or using edit command with 0 as amt/ parameter

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: sudarshan2401/ped#1

**Comment by woojiahao** [comment]
The documentation surrounding the support amount values were not clear on why this is possible. Will be improving the clarity of this in the upcoming UG changes, great catch!
