### ISSUE TITLE
[PE-D][Tester C] Error message does not match

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S1-CS2103-T16-3/tp#159]
![image.png](https://raw.githubusercontent.com/jrchoo/ped/main/files/1703184c-97ec-4e93-922f-7ebb250a6782.png)

![image.png](https://raw.githubusercontent.com/jrchoo/ped/main/files/8eab3806-258d-4217-ab84-3bd929e52f4c.png)

When an index of 0 is given, the error message does not address it unlike when the index supplied is 10 (index out of bounds).

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: jrchoo/ped#1

**Comment by jamz903** [comment]
Similar issue was addressed in Issue #150.

Since 0 is not a positive integer, the error message actually addresses it by notifying the user that for the command to be valid a positive integer must be given.
