### ISSUE TITLE
[PE-D][Tester A] Repeated visuals in UG

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S1-CS2103-T16-3/tp#160]
### Description
The repetitive comparison between input and output in the examples can be omitted.

### Context
Some input and output visuals only have changes in the command box and results display, this causes user to feel lost when looking at the UG

### Suggestions
The visuals can be omitted and show expected messages instead.

-------------
Labels: `severity.Low` `type.DocumentationBug`
original: Ken-Lai/ped#2

**Comment by lipwei1808** [comment]
See #169
