### ISSUE TITLE
[PE-D][Tester C] Error message

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S1-CS2103-T16-3/tp#162]
![image.png](https://raw.githubusercontent.com/jrchoo/ped/main/files/224230ab-fc5f-48bb-8bf6-312b6a43ae29.png)

![image.png](https://raw.githubusercontent.com/jrchoo/ped/main/files/dfccca72-c885-44c1-86e0-6972e78dfaf9.png)

When index is 0, error message is not representative of the issue.

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: jrchoo/ped#3

**Comment by jamz903** [comment]
Similar issue was addressed in #150 , #159 .

When the index is 0, the index provided is indeed invalid - but more than that, the index will **always** be invalid. This is why we specified this as a _invalid command format_ error, particularly informing users that the **index needs to be positive** (1 and above) for this command.

**Comment by woojiahao** [comment]
Will also be improving existing documentation on this
